### PR TITLE
agent_sim: Fix order of parameters

### PR DESCRIPTION
**Pull request by toabctl**
When calling agent_sim_process(), the order of the parameters was wrong.

### CODE REVIEW

**Comment by mhoppal** [comment]
why this instead of https://github.com/hpcloud-mon/monasca-perf/blob/master/scale_perf/agent_simulator.py

**Comment by toabctl** [comment]
> why this instead of https://github.com/hpcloud-mon/monasca-perf/blob/master/scale_perf/agent_simulator.py

@mhoppal I didn't saw that script. I'll have a look

**Comment by toabctl** [comment]
@mhoppal hm. should we delete the ```agent_sim``` script completly?

**Comment by mhoppal** [comment]
probably unless you see any use out of it? We really havent done a good job keeping only the scripts we use.

**Comment by toabctl** [comment]
I don't plan to work on this. Closing.

**Pull request closed without merging**
